const VERSION='1.0.0';
const PROJECTS=[
 {id:'landing',name:'Landing page',base:36,min:1800,max:6500},{id:'corporate',name:'Web corporativa',base:70,min:3500,max:12000},{id:'ecommerce',name:'E-commerce',base:150,min:9000,max:35000},{id:'webapp',name:'Plataforma web / SaaS',base:210,min:15000,max:65000},{id:'mobile',name:'Aplicación móvil',base:260,min:25000,max:90000},{id:'erp',name:'ERP / sistema empresarial',base:480,min:40000,max:180000},{id:'crm',name:'CRM',base:280,min:22000,max:90000},{id:'inventory',name:'Inventario / logística',base:220,min:16000,max:70000},{id:'automation',name:'Automatización',base:75,min:4500,max:30000},{id:'dashboard',name:'Dashboard / BI',base:100,min:6500,max:30000},{id:'api',name:'API / backend',base:120,min:9000,max:40000},{id:'ai',name:'IA / agente inteligente',base:220,min:12000,max:100000},{id:'custom',name:'Software a medida',base:180,min:12000,max:100000}
];
const COMPLEXITIES=[{id:'basic',name:'Básica',desc:'Flujos directos y pocas reglas',mult:1},{id:'medium',name:'Media',desc:'Roles, reportes y lógica moderada',mult:1.25},{id:'high',name:'Alta',desc:'Procesos críticos e integraciones',mult:1.55},{id:'enterprise',name:'Empresarial',desc:'Escala, auditoría y resiliencia',mult:1.95}];
const MODULES=[
 ['auth','Login y recuperación','Acceso',12,'Baja'],['roles','Roles y permisos','Acceso',18,'Media'],['users','Gestión de usuarios','Acceso',16,'Media'],['dashboard','Dashboard ejecutivo','Analítica',24,'Media'],['reports','Reportes configurables','Analítica',30,'Alta'],['pdf','Generación de PDF','Documentos',12,'Media'],['excel','Excel / importación','Documentos',15,'Media'],['clients','Clientes','Comercial',18,'Media'],['quotes','Cotizaciones','Comercial',28,'Alta'],['sales','Ventas','Comercial',32,'Alta'],['purchases','Compras','Operación',30,'Alta'],['inventory','Inventario','Operación',45,'Alta'],['warehouse','Almacenes y ubicaciones','Operación',38,'Alta'],['pos','Punto de venta','Operación',42,'Alta'],['payments','Pagos y conciliación','Finanzas',40,'Alta'],['billing','Facturación electrónica','Finanzas',55,'Muy alta'],['subscriptions','Suscripciones','Finanzas',35,'Alta'],['workflow','Flujos y aprobaciones','Operación',36,'Alta'],['notifications','Notificaciones','Comunicación',14,'Media'],['chat','Chat en tiempo real','Comunicación',32,'Alta'],['email','Correos transaccionales','Comunicación',12,'Media'],['calendar','Calendario / agenda','Productividad',24,'Media'],['files','Archivos y documentos','Documentos',20,'Media'],['search','Búsqueda avanzada','UX',18,'Media'],['offline','Modo offline / sincronización','Plataforma',40,'Muy alta'],['scanner','Código de barras / QR','Dispositivo',25,'Alta'],['gps','GPS y geolocalización','Dispositivo',38,'Alta'],['maps','Mapas y rutas','Dispositivo',36,'Alta'],['signature','Firma digital','Documentos',28,'Alta'],['audit','Auditoría y logs','Seguridad',30,'Alta'],['2fa','Autenticación 2FA','Seguridad',18,'Alta'],['ai-assistant','Asistente IA','IA',50,'Muy alta'],['ai-analysis','Análisis predictivo','IA',75,'Muy alta'],['multitenant','Multiempresa / multitenant','Arquitectura',55,'Muy alta'],['admin','Panel administrador','Operación',30,'Alta'],['settings','Configuración general','Operación',14,'Media']
].map(([id,name,category,hours,level])=>({id,name,category,hours,level}));
const INTEGRATIONS=[['sheets','Google Sheets',12],['firebase','Firebase',18],['supabase','Supabase',18],['whatsapp','WhatsApp API',28],['openai','OpenAI / IA',32],['maps-api','Google Maps',24],['payment','Pasarela de pago',34],['sunat','SUNAT',48],['reniec','RENIEC',30],['erp-api','ERP externo',40],['email-api','Servicio de correo',12],['storage','Cloud storage',16]].map(([id,name,hours])=>({id,name,hours}));
const TECH={frontend:[['html','HTML/CSS/JS',1],['react','React',1.08],['vue','Vue',1.07],['angular','Angular',1.18],['flutter','Flutter',1.2],['reactnative','React Native',1.2],['native','Nativo iOS/Android',1.38]],backend:[['none','Sin backend',.9],['appscript','Apps Script',.98],['node','Node.js',1.08],['python','Python',1.1],['php','PHP/Laravel',1.06],['java','Java/Spring',1.2],['dotnet','.NET',1.18]],database:[['none','Sin base de datos',.9],['firebase','Firebase / Firestore',1],['supabase','Supabase / PostgreSQL',1.02],['mysql','MySQL',1.04],['postgres','PostgreSQL',1.06],['sqlserver','SQL Server',1.14],['mongo','MongoDB',1.08]],hosting:[['github','GitHub Pages',1],['firebase','Firebase Hosting',1.01],['vercel','Vercel / Netlify',1.01],['cloud','Cloud administrado',1.08],['vps','VPS',1.1],['onprem','Servidor propio',1.2]]};
const DEFAULT_SETTINGS={costRate:42,sellRate:95,targetMargin:38,weeklyHours:30,taxRate:18,fxRate:3.75,overhead:12,maxDiscount:10};
let settings=JSON.parse(localStorage.getItem('qf_settings')||'null')||{...DEFAULT_SETTINGS};
let state={step:1,complexity:'medium',modules:[],integrations:[],scenario:'recommended'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,currency=$('#currency')?.value||'PEN')=>new Intl.NumberFormat('es-PE',{style:'currency',currency,maximumFractionDigits:0}).format(currency==='USD'?n/settings.fxRate:n);
function init(){populate();bind();loadSettings();calculate();renderCatalog();renderHistory();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
function populate(){PROJECTS.forEach(p=>$('#projectType').add(new Option(p.name,p.id))); COMPLEXITIES.forEach(c=>$('#complexityChoices').insertAdjacentHTML('beforeend',`<button class="choice ${c.id===state.complexity?'active':''}" data-complexity="${c.id}"><strong>${c.name}</strong><span>${c.desc}</span></button>`));renderModules();renderIntegrations();Object.entries(TECH).forEach(([key,items])=>items.forEach(([id,name])=>$('#'+key).add(new Option(name,id))));}
function renderModules(filter=''){const grid=$('#moduleGrid');grid.innerHTML='';MODULES.filter(m=>m.name.toLowerCase().includes(filter.toLowerCase())).forEach(m=>grid.insertAdjacentHTML('beforeend',`<label class="module-card ${state.modules.includes(m.id)?'selected':''}"><input type="checkbox" value="${m.id}" ${state.modules.includes(m.id)?'checked':''}><span><strong>${m.name}</strong><span>${m.category} · ${m.hours} h</span></span></label>`));bindChecks();updateModuleCount();}
function renderIntegrations(){INTEGRATIONS.forEach(i=>$('#integrationGrid').insertAdjacentHTML('beforeend',`<label class="module-card"><input type="checkbox" value="${i.id}"><span><strong>${i.name}</strong><span>+${i.hours} h base</span></span></label>`));}
function bindChecks(){$$('#moduleGrid input').forEach(input=>input.onchange=()=>{state.modules=input.checked?[...new Set([...state.modules,input.value])]:state.modules.filter(x=>x!==input.value);input.closest('.module-card').classList.toggle('selected',input.checked);updateModuleCount();calculate();});}
function bind(){
 $$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view)); $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open'); $('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('qf_theme',document.body.classList.contains('dark')?'dark':'light')}; if(localStorage.getItem('qf_theme')==='dark')document.body.classList.add('dark');
 $$('#complexityChoices .choice').forEach(b=>b.onclick=()=>{$$('#complexityChoices .choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.complexity=b.dataset.complexity;calculate();});
 $('#moduleSearch').oninput=e=>renderModules(e.target.value); $('#integrationGrid').onchange=e=>{if(e.target.matches('input')){state.integrations=e.target.checked?[...new Set([...state.integrations,e.target.value])]:state.integrations.filter(x=>x!==e.target.value);e.target.closest('.module-card').classList.toggle('selected',e.target.checked);calculate();}};
 $$('input,select,textarea').forEach(el=>el.addEventListener('input',calculate)); $('#contingency').oninput=e=>{$('#contingencyOut').textContent=e.target.value+'%';calculate();};
 $('#nextBtn').onclick=()=>{if(state.step<6){state.step++;showStep()}else saveQuote()}; $('#prevBtn').onclick=()=>{if(state.step>1){state.step--;showStep()}}; $('#saveBtn').onclick=saveQuote; $('#resetBtn').onclick=resetForm; $('#printBtn').onclick=()=>window.print();
 $$('.scenario').forEach(b=>b.onclick=()=>{$$('.scenario').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.scenario=b.dataset.scenario;calculate();});
 $('#exportHistoryBtn').onclick=exportHistory; $('#defaultsBtn').onclick=()=>{settings={...DEFAULT_SETTINGS};loadSettings();saveSettings();calculate();toast('Configuración restaurada')};
 ['costRate','sellRate','targetMargin','weeklyHours','taxRate','fxRate','overhead','maxDiscount'].forEach(id=>$('#'+id).oninput=()=>{settings[id]=Number($('#'+id).value);saveSettings();calculate();});
}
function switchView(view){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view+'View').classList.add('active');const map={builder:['ESTIMACIÓN COMERCIAL','Nueva cotización'],history:['REGISTROS','Historial'],catalog:['BASE DE CÁLCULO','Catálogo'],settings:['MOTOR FINANCIERO','Configuración']};$('#viewEyebrow').textContent=map[view][0];$('#viewTitle').textContent=map[view][1];$('#sidebar').classList.remove('open');}
function showStep(){$$('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===state.step));$('#stepLabel').textContent=`Paso ${state.step} de 6`;$('#progressPct').textContent=Math.round(state.step/6*100)+'%';$('#progressBar').style.width=(state.step/6*100)+'%';$('#prevBtn').style.visibility=state.step===1?'hidden':'visible';$('#nextBtn').textContent=state.step===6?'Guardar cotización':'Continuar';window.scrollTo({top:0,behavior:'smooth'});calculate();}
function val(id,fallback=0){return Number($('#'+id)?.value||fallback)}
function calculate(){
 const project=PROJECTS.find(p=>p.id===$('#projectType').value)||PROJECTS[0], comp=COMPLEXITIES.find(c=>c.id===state.complexity)||COMPLEXITIES[1];
 const moduleHours=state.modules.reduce((a,id)=>a+(MODULES.find(m=>m.id===id)?.hours||0),0), integrationHours=state.integrations.reduce((a,id)=>a+(INTEGRATIONS.find(i=>i.id===id)?.hours||0),0);
 const screenHours=Math.max(0,val('screens',8)-3)*4, extras=val('design')+val('support')+val('training');
 let raw=project.base+moduleHours+integrationHours+screenHours+extras;
 const techMult=['frontend','backend','database','hosting'].reduce((a,k)=>a*(TECH[k].find(t=>t[0]===$('#'+k).value)?.[2]||1),1);
 const scopeMult=comp.mult*val('users',1)*val('platforms',1)*val('quality',1)*val('requirements',1)*val('urgency',1);
 let hours=raw*techMult*scopeMult; const contingency=val('contingency',12)/100; hours*=1+contingency;
 const overhead=settings.overhead/100; const internal=hours*settings.costRate*(1+overhead); const scenarioMult={competitive:.9,recommended:1,premium:1.18}[state.scenario];
 const margin=Math.min(.75,Math.max(.05,settings.targetMargin/100+({competitive:-.06,recommended:0,premium:.08}[state.scenario])));
 const costPrice=internal/(1-margin); const ratePrice=hours*settings.sellRate; let price=Math.max(costPrice,ratePrice)*scenarioMult;
 const benchmarkMin=project.min*(.75+comp.mult*.25), benchmarkMax=project.max*(.7+comp.mult*.3); price=Math.max(price,benchmarkMin*.72);
 const profit=price-internal, weeks=Math.max(1,hours/settings.weeklyHours), lower=Math.max(internal*1.12,price*.88), upper=price*1.18;
 const risk=Math.round((comp.mult+val('requirements',1)+val('urgency',1)+val('platforms',1)-4)*28+contingency*100); const confidence=risk<25?'Alta':risk<55?'Media':'Baja';
 $('#estimatePrice').textContent=fmt(price);$('#totalHours').textContent=Math.round(hours)+' h';$('#duration').textContent=(weeks<10?weeks.toFixed(1):Math.round(weeks))+' sem.';$('#internalCost').textContent=fmt(internal);$('#profit').textContent=fmt(profit);$('#marginLabel').textContent='Margen '+Math.round(profit/price*100)+'%';$('#priceRange').textContent=`${fmt(lower)} — ${fmt(upper)}`;$('#confidence').textContent=confidence;
 renderEffort(project.base,moduleHours,integrationHours,screenHours+extras,hours); renderRisks(comp); renderReview({project,comp,hours,weeks,price,internal,profit});
 const signal=price<benchmarkMin?'Precio agresivo: está debajo del benchmark de referencia.':price>benchmarkMax?'Precio alto: valida valor diferencial, alcance y comprador objetivo.':'Precio alineado con el rango competitivo del tipo de proyecto.';$('#marketSignal').textContent=signal;
 state.last={project,comp,hours,weeks,price,internal,profit,lower,upper,benchmarkMin,benchmarkMax};
}
function renderEffort(base,mods,ints,extras,total){const arr=[['Base',base],['Módulos',mods],['Integraciones',ints],['Diseño y soporte',extras]];const sum=arr.reduce((a,x)=>a+x[1],0)||1;$('#effortBars').innerHTML=arr.map(([n,v])=>`<div class="effort-row"><div class="effort-meta"><span>${n}</span><span>${Math.round(v)} h</span></div><div class="effort-track"><div style="width:${Math.max(3,v/sum*100)}%"></div></div></div>`).join('');}
function renderRisks(comp){const risks=[['Complejidad',comp.name],['Requisitos',$('#requirements').selectedOptions[0].text],['Urgencia',$('#urgency').selectedOptions[0].text],['Contingencia',$('#contingency').value+'%']];$('#riskList').innerHTML=risks.map(x=>`<div class="risk-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');}
function renderReview(x){$('#reviewBox').innerHTML=[['Proyecto',$('#projectName').value||'Sin nombre'],['Tipo',x.project.name],['Complejidad',x.comp.name],['Módulos',state.modules.length],['Esfuerzo',Math.round(x.hours)+' horas'],['Duración',x.weeks.toFixed(1)+' semanas'],['Precio sugerido',fmt(x.price)],['Utilidad estimada',fmt(x.profit)]].map(([a,b])=>`<div class="review-item"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function updateModuleCount(){$('#moduleCount').textContent=state.modules.length+' seleccionados'}
function collect(){return{version:VERSION,id:crypto.randomUUID?.()||Date.now().toString(),createdAt:new Date().toISOString(),name:$('#projectName').value||'Proyecto sin nombre',client:$('#clientName').value||'Sin cliente',description:$('#description').value,projectType:$('#projectType').value,currency:$('#currency').value,complexity:state.complexity,screens:val('screens'),users:$('#users').value,platforms:$('#platforms').value,design:$('#design').value,quality:$('#quality').value,modules:state.modules,integrations:state.integrations,frontend:$('#frontend').value,backend:$('#backend').value,database:$('#database').value,hosting:$('#hosting').value,requirements:$('#requirements').value,urgency:$('#urgency').value,support:$('#support').value,training:$('#training').value,contingency:$('#contingency').value,scenario:state.scenario,notes:$('#commercialNotes').value,result:state.last};}
function saveQuote(){const q=collect(),history=JSON.parse(localStorage.getItem('qf_quotes')||'[]');history.unshift(q);localStorage.setItem('qf_quotes',JSON.stringify(history.slice(0,100)));renderHistory();toast('Cotización guardada correctamente');}
function renderHistory(){const list=$('#historyList');if(!list)return;const h=JSON.parse(localStorage.getItem('qf_quotes')||'[]');list.innerHTML=h.length?h.map(q=>`<article class="history-item"><div><strong>${q.name}</strong><p>${q.client} · ${new Date(q.createdAt).toLocaleDateString('es-PE')} · ${PROJECTS.find(p=>p.id===q.projectType)?.name||''}</p></div><div class="history-item-actions"><strong>${fmt(q.result?.price||0,q.currency)}</strong><button class="btn secondary" onclick="deleteQuote('${q.id}')">Eliminar</button></div></article>`).join(''):'<div class="note-box">Aún no hay cotizaciones guardadas.</div>';}
window.deleteQuote=id=>{const h=JSON.parse(localStorage.getItem('qf_quotes')||'[]').filter(q=>q.id!==id);localStorage.setItem('qf_quotes',JSON.stringify(h));renderHistory();toast('Cotización eliminada')};
function exportHistory(){const data=localStorage.getItem('qf_quotes')||'[]',blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quoteforge-cotizaciones.json';a.click();URL.revokeObjectURL(a.href);}
function renderCatalog(){$('#catalogBody').innerHTML=MODULES.map(m=>`<tr><td>${m.name}</td><td>${m.category}</td><td>${m.hours} h</td><td>${m.level}</td></tr>`).join('');}
function loadSettings(){Object.keys(DEFAULT_SETTINGS).forEach(k=>$('#'+k).value=settings[k]);}
function saveSettings(){localStorage.setItem('qf_settings',JSON.stringify(settings));}
function resetForm(){if(!confirm('¿Reiniciar la cotización actual?'))return;document.querySelectorAll('input[type="text"],textarea').forEach(x=>x.value='');document.querySelectorAll('input[type="checkbox"]').forEach(x=>{x.checked=false;x.closest('.module-card')?.classList.remove('selected')});state={step:1,complexity:'medium',modules:[],integrations:[],scenario:'recommended'};$('#screens').value=8;$('#contingency').value=12;$('#contingencyOut').textContent='12%';$$('.choice').forEach(x=>x.classList.toggle('active',x.dataset.complexity==='medium'));showStep();updateModuleCount();toast('Formulario reiniciado');}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
init();
